# Generated by Django 5.1.6 on 2025-03-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('miscellaneous', models.CharField(blank=True, max_length=100, null=True)),
                ('scraping_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('offer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('url', models.TextField()),
                ('img_url', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.countryitem')),
            ],
            options={
                'unique_together': {('product_id', 'country')},
            },
        ),
    ]
