# Generated by Django 5.1.6 on 2025-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_currencyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='unit',
            field=models.CharField(choices=[('€', 'EUR'), ('£', 'GBP'), ('$', 'USD')], max_length=100, null=True),
        ),
    ]
